### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by nevenan** [alptium/nevena.nesovanovic#2]

**Comment by nevenan** [comment]
I have done this task @valentinacupac

**Comment by valentinajemuovic** [comment]
@nevenan, it's correct, but just one small formatting improvement, I see you have two blank lines on lines 6 & 7, could you delete one of the blank lines, since just one is enough, based on formatting conventions.

**Comment by nevenan** [comment]
@valentinacupac I think it's done now.

**Comment by valentinajemuovic** [comment]
@nevenan, correct.
