### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by nevenan** [alptium/nevena.nesovanovic#3]

**Comment by nevenan** [comment]
I have done Calculator project @valentinacupac

**Comment by valentinajemuovic** [comment]
@nevenan, did you push the project.
I checked here https://github.com/alptium/nevena.nesovanovic and I cannot see it.

**Comment by nevenan** [comment]
@valentinacupac  I think I've pushed the project now. Please review it.

**Comment by valentinajemuovic** [comment]
@nevenan:
1. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 2 (naming rules for Java projects)
2. Indentaton on lines 37 & 39 is not correct, it should be one more tab there, see my example https://github.com/alptium/valentina.cupac/blob/master/calculator/src/org/alptium/valentinacupac/samples/calculator/Main.java

**Comment by valentinajemuovic** [comment]
Discontinued, closing ticket.
