### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by nevenan** [alptium/nevena.nesovanovic#5]

**Comment by nevenan** [comment]
@valentinacupac  I have done Gradebook project

**Comment by valentinajemuovic** [comment]
@nevenan, did you do this project yourself or did you get the code from one of the other participants?

**Comment by nevenan** [comment]
@valentinacupac I copied it from the internet search, I will re-do it.

**Comment by valentinajemuovic** [comment]
Discontinued, closing ticket.
