### ISSUE TITLE
Project Management - Basic Setup

### ISSUE THREAD

**Issue by nevenan** [alptium/nevena.nesovanovic#6]

**Comment by valentinajemuovic** [comment]
Hi @nevenan, I see you created this ticket and did the setup in alptium/nevena.nesovanovic.

However, this needs to be done inside alptium/restaurant... Furthermore, any future tasks regarding Alptium Restaurant must go there, since it's a group project. Please re-try.

**Comment by valentinajemuovic** [comment]
Discontinued, closing ticket.
